backend/config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :missions do
      resources :spots
    end

    resources :users
    resources :user_spot_links

    root 'missions#index'
  end

  namespace :api do
    resources :missions do
      resources :spots do
        resources :user_spot_links
      end
    end
  end

  root to: redirect('/admin')

end

backend/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

backend/app/models/mission.rb
class Mission < ApplicationRecord

  # Associations

  has_many :spots, :dependent => :destroy
  has_many :user_spot_links, :through => :spots

  # CarrierWave

  mount_uploader :picture, PictureUploader

  # Validation

  validates :name, :presence => { :message => "Le nom est obligatoire." }

end

backend/app/models/spot.rb
class Spot < ApplicationRecord

  # Associations

  belongs_to :mission

  has_many :user_spot_links, :dependent => :destroy

  # CarrierWave

  mount_uploader :picture, PictureUploader

  # Validation

  validates :name, :presence => { :message => "Le nom est obligatoire." }

  # Methods

  def geolocalized?
    latitude.present? && longitude.present?
  end

end

backend/app/models/user.rb
class User < ApplicationRecord

  # Associations

  has_many :user_spot_links, :dependent => :destroy
  has_many :spots, :through => :user_spot_links
  has_many :missions, :through => :spots

end

backend/app/models/user_spot_link.rb
class UserSpotLink < ApplicationRecord

  # Associations

  belongs_to :user
  belongs_to :spot

  # CarrierWave

  mount_uploader :picture, PictureUploader

end

backend/app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  protect_from_forgery with: :exception
  layout 'admin'
  before_action :http_basic_auth

  private

  def http_basic_auth
    if Rails.env.production? && ENV['HTTP_BASIC_AUTH_USERNAME'].present?
      authenticate_or_request_with_http_basic do |username, password|
        username == ENV['HTTP_BASIC_AUTH_USERNAME'] &&
        password == ENV['HTTP_BASIC_AUTH_PASSWORD']
      end
    end
  end
end

backend/app/controllers/admin/missions_controller.rb
class Admin::MissionsController < Admin::BaseController
  def index
    @missions = Mission.order(:name)
  end

  def new
    @mission = Mission.new
    render 'form'
  end

  def create
    @mission = Mission.new(strong_params)

    if @mission.save
      redirect_to admin_missions_path
    else
      set_flash_now_errors(@mission)
      render 'form'
    end
  end

  def edit
    @mission = Mission.find(params[:id])
    render 'form'
  end

  def update
    @mission = Mission.find(params[:id])

    if @mission.update_attributes(strong_params)
      redirect_to admin_missions_path
    else
      set_flash_now_errors(@mission)
      render 'form'
    end
  end

  def destroy
    @mission = Mission.find(params[:id])
    @mission.destroy
    redirect_to admin_missions_path
  end

  private

  def strong_params
    params.require(:mission).permit(
      :name, :tagline, :description, :picture, :picture_cache, :latitude, :longitude
    )
  end
end

backend/app/controllers/admin/spots_controller.rb
class Admin::SpotsController < Admin::BaseController

  before_action :find_mission

  def index
    @spots = @mission.spots.order(:name)
  end

  def new
    @spot = @mission.spots.new
    render 'form'
  end

  def create
    @spot = @mission.spots.new(strong_params)

    if @spot.save
      redirect_to admin_mission_spots_path(@mission)
    else
      set_flash_now_errors(@spot)
      render 'form'
    end
  end

  def edit
    @spot = @mission.spots.find(params[:id])
    render 'form'
  end

  def update
    @spot = @mission.spots.find(params[:id])

    if @spot.update_attributes(strong_params)
      redirect_to admin_mission_spots_path(@mission)
    else
      set_flash_now_errors(@spot)
      render 'form'
    end
  end

  def destroy
    @spot = @mission.spots.find(params[:id])
    @spot.destroy
    redirect_to admin_mission_spots_path(@mission)
  end

  private

  def find_mission
    @mission = Mission.find(params[:mission_id])
  end

  def strong_params
    params.require(:spot).permit(
      :name, :description, :picture, :picture_cache, :latitude, :longitude
    )
  end
end

backend/app/controllers/admin/user_spot_links_controller.rb
class Admin::UserSpotLinksController < Admin::BaseController
  def index
    @user_spot_links = UserSpotLink.where.not(:picture => nil)
                                   .order(:updated_at => :desc)
                                   .limit(100)
  end
end

backend/app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to admin_users_path
  end
end

backend/app/controllers/api/base_controller.rb
class Api::BaseController < ApplicationController

  before_action :find_or_create_user

  def find_or_create_user
    device_id = params[:device_id].to_s.strip

    if device_id.present?
      @user = User.where(device_id: device_id).first_or_create
    end
  end

end

backend/app/controllers/api/missions_controller.rb
class Api::MissionsController < Api::BaseController
  def index
    @missions = Mission.all
  end
end

backend/app/controllers/api/spots_controller.rb
class Api::SpotsController < Api::BaseController

  before_action :find_mission

  def index
    @spots = @mission.spots
  end

  private

  def find_mission
    @mission = Mission.find(params[:mission_id])
  end
end

backend/app/controllers/api/user_spot_links_controller.rb
class Api::UserSpotLinksController < Api::BaseController
  def create
    if @user.present?
      @mission        = Mission.find(params[:mission_id])
      @spot           = @mission.spots.find(params[:spot_id])
      @user_spot_link = @spot.user_spot_links.where(:user_id => @user.id).first_or_initialize

      if params[:user_spot_link][:picture]
        Rails.logger.info "je suis dans le if"

        tmp_path = "#{Rails.root}/tmp/#{UUIDTools::UUID.random_create}.jpg"
        data     = Base64.decode64(params[:user_spot_link][:picture])

        Rails.logger.info tmp_path

        File.open(tmp_path, 'wb') do |file|
          file.write(data)
        end

        @user_spot_link.picture = File.new(tmp_path)
        @user_spot_link.save!
        FileUtils.rm(tmp_path)
      else
        Rails.logger.info "je suis dans le else"
        @user_spot_link.destroy! if @user_spot_link.persisted?
      end
    end

    render :json => { :success => true }
  end
end

backend/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def set_flash_now_errors(object)
    if object.errors.any?
      flash.now[:alert] = object.errors.messages.values.join('<br />').html_safe
    end
  end
end

backend/app/helpers/application_helper.rb
module ApplicationHelper
  def fa(name, suffix = nil)
    if suffix.present?
      "#{content_tag(:i, '', :class => "fa fa-#{name}")}&nbsp;#{suffix}".html_safe
    else
      content_tag(:i, '', :class => "fa fa-#{name}")
    end
  end
end

backend/app/views/admin/missions/form.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-6 col-md-offset-3">
      <h1><%= params[:action].in?(['new', 'create']) ? "Ajouter une mission" : "Modifier une mission" %></h1>

      <%= render 'shared/flash' %>

      <%= form_for([:admin, @mission], :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Nom', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :tagline, 'Accroche', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :tagline, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, 'Description', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_area :description, :class => 'form-control', :rows => 5 %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :picture, 'Photo', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.file_field :picture, :class => 'form-control' %>

            <%= f.hidden_field :picture_cache %>

            <% if @mission.picture.present? %>
              <br />
              <img src="<%= @mission.picture.url(:preview) %>" class="thumbnail" />
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :latitude, 'Latitude', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :latitude, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :longitude, 'Longitude', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :longitude, :class => 'form-control' %>
          </div>
        </div>

        <div class="actions">
          <%= link_to 'Annuler', admin_missions_path, :class => 'btn btn-sm btn-default' %>
          <%= f.submit 'Enregistrer', :class => 'btn btn-sm btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

backend/app/views/admin/missions/index.html.erb
<div class="container">
  <div class="row">
    <ol class="breadcrumb">
      <li><%= link_to 'Missions', admin_missions_path %></li>
    </ol>

    <%= link_to 'Ajouter une mission', new_admin_mission_path, :class => 'btn btn-xs btn-primary pull-right btn-new' %>

    <table class="table">
      <thead>
        <tr>
          <th>Nom</th>
          <th>Accroche</th>
          <th>Photo</th>
          <th class="number">Points</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @missions.each do |mission| %>
          <tr>
            <td><%= link_to mission.name, admin_mission_spots_path(mission) %></td>
            <td><%= mission.tagline %></td>
            <td><img src="<%= mission.picture.url(:tiny) %>" /></td>
            <td class="number"><%= link_to mission.spots.count, admin_mission_spots_path(mission) %></td>

            <td class="actions">
              <%= link_to fa('edit'),   edit_admin_mission_path(mission), :class => 'btn btn-xs btn-default' %>
              <%= link_to fa('remove'), admin_mission_path(mission),      :class => 'btn btn-xs btn-danger', :data => { :confirm => "Supprimer cette mission ?" }, :method => :delete %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

backend/app/views/admin/shared/_header.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="row">
      <div class="navbar-header">
        <a class="navbar-brand" href="<%= root_path %>">Cliché</a>
      </div>

      <ul class="nav navbar-nav sections">
        <% missions_tab_active        = params[:controller] == 'admin/missions' || params[:controller] == 'admin/spots' %>
        <% users_tab_active           = params[:controller] == 'admin/users'    %>
        <% user_spot_links_tab_active = params[:controller] == 'admin/user_spot_links' %>

        <li<%= ' class="active"'.html_safe if missions_tab_active %>>
          <a href="<%= admin_missions_path %>">Missions</a>
        </li>

        <li<%= ' class="active"'.html_safe if users_tab_active %>>
          <a href="<%= admin_users_path %>">Utilisateurs</a>
        </li>

        <li<%= ' class="active"'.html_safe if user_spot_links_tab_active %>>
          <a href="<%= admin_user_spot_links_path %>">Photos</a>
        </li>
      </ul>

      <ul class="nav navbar-nav pull-right">
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            John Doe <i class="fa fa-caret-down"></i>
          </a>
        </li>
      </ul>
    </div>
  </div>
</nav>

backend/app/views/admin/spots/form.html.erb
<div class="container">
  <div class="row">
    <div class="panel col-md-6 col-md-offset-3">
      <h1><%= params[:action].in?(['new', 'create']) ? "Ajouter un point" : "Modifier un point" %></h1>

      <%= render 'shared/flash' %>

      <%= form_for([:admin, @mission, @spot], :html => { :class => 'form-horizontal' }) do |f| %>
        <div class="form-group">
          <%= f.label :name, 'Nom', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :name, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :description, 'Description', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_area :description, :class => 'form-control', :rows => 5 %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :picture, 'Photo', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.file_field :picture, :class => 'form-control' %>

            <%= f.hidden_field :picture_cache %>

            <% if @spot.picture.present? %>
              <br />
              <img src="<%= @spot.picture.url(:sketch) %>" class="thumbnail" />
            <% end %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :latitude, 'Latitude', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :latitude, :class => 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :longitude, 'Longitude', :class => 'control-label col-md-3' %>

          <div class="col-md-9">
            <%= f.text_field :longitude, :class => 'form-control' %>
          </div>
        </div>

        <div class="actions">
          <%= link_to 'Annuler', admin_mission_spots_path(@mission), :class => 'btn btn-sm btn-default' %>
          <%= f.submit 'Enregistrer', :class => 'btn btn-sm btn-primary' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

backend/app/views/admin/spots/index.html.erb
<div class="container">
  <div class="row">
    <ol class="breadcrumb">
      <li><%= link_to 'Missions', admin_missions_path %></li>
      <li><%= @mission.name %></li>
      <li class="active"><%= link_to 'Points', admin_mission_spots_path(@mission) %></li>
    </ol>

    <%= link_to 'Ajouter un point', new_admin_mission_spot_path(@mission), :class => 'btn btn-xs btn-primary pull-right btn-new' %>

    <% if @spots.any? %>
      <table class="table">
        <thead>
          <tr>
            <th>Nom</th>
            <th>Photo</th>
            <th class="center">Géolocalisé</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @spots.each do |spot| %>
            <tr>
              <td><%= spot.name %></td>
              <td><img src="<%= spot.picture.url(:tiny_sketch) %>" /></td>
              <td class="center"><%= spot.geolocalized? ? fa('check') : fa('times') %></td>

              <td class="actions">
                <%= link_to fa('edit'),   edit_admin_mission_spot_path(@mission, spot), :class => 'btn btn-xs btn-default' %>
                <%= link_to fa('remove'), admin_mission_spot_path(@mission, spot),      :class => 'btn btn-xs btn-danger', :data => { :confirm => "Supprimer cette mission ?" }, :method => :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

backend/app/views/admin/user_spot_links/index.html.erb
<div class="container">
  <div class="row">

    <% if @user_spot_links.any? %>
      <table class="table">
        <thead>
          <tr>
            <th>ID du périphérique</th>
            <th>Mission</th>
            <th>Point</th>
            <th>Photo sketch</th>
            <th>Photo</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @user_spot_links.each do |link| %>
            <tr>
              <td><%= link.user.device_id %></td>
              <td><%= link.spot.mission.name %></td>
              <td><%= link.spot.name %></td>
              <td><img src="<%= link.spot.picture.url(:sketch) %>" /></td>
              <td><img src="<%= link.picture.url(:preview) %>" /></td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

backend/app/views/admin/users/index.html.erb
<div class="container">
  <div class="row">

    <% if @users.any? %>
      <table class="table">
        <thead>
          <tr>
            <th>ID du périphérique</th>
            <th class="number">Missions</th>
            <th class="number">Photos</th>
            <th></th>
          </tr>
        </thead>

        <tbody>
          <% @users.each do |user| %>
            <tr>
              <td><%= user.device_id %></td>
              <td class="number"><%= user.missions.count %></td>
              <td class="number"><%= user.user_spot_links.count %></td>

              <td class="actions">
                <%= link_to fa('remove'), admin_user_path(user), :class => 'btn btn-xs btn-danger', :data => { :confirm => "Supprimer cet utilisateur et ses données ?" }, :method => :delete %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

backend/app/views/layouts/admin.html.erb
<!DOCTYPE html>

<html lang="<%= session[:locale] ? session[:locale] : 'en' %>"
      id="<%= "#{params[:controller].gsub('/', '-')}-#{params[:action]}" %>"
      data-rails-env="<%= Rails.env %>">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <% if yield(:title).present? %>
      <% title = "#{yield(:title)} - Cliché" %>
    <% else %>
      <% title = "Cliché" %>
    <% end %>

    <title>
      <%= title %>
    </title>

    <%= stylesheet_link_tag("application", media: "all") %>

    <%= yield :special_header %>

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'admin/shared/header' %>

    <%= yield %>

    <%= javascript_include_tag 'application' %>
  </body>
</html>

backend/app/views/shared/_flash.html.erb
<% if flash[:notice].present? %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:notice] %>
  </div>
<% end %>

<% if flash[:alert].present? %>
  <div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= flash[:alert] %>
  </div>
<% end %>